version: '3.3'
services:
    novel:
        ports:
            - '80:80'
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site/wwwroot/xs/:/var/www/html/
        container_name: novel
        image: 'mrzqd/novel:latest'




        version: '3.9'

volumes:
  web-html:
    name: web-html
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volumes/web/html

services:
  nginx:
    image: yxs970707/deploy-web-demo:1.0.0
    container_name: web
    restart: always
    ports:
      - 7777:80
    volumes:
      - web-html:/usr/share/nginx/html